FileNotFoundError 1
shutil.ReadError 6
FileExistsError 4
RuntimeError 1
OSError 14611
PermissionError 5529


!!!!!!!!!!!!!!!!!!!!!! Exception: <class 'FileNotFoundError'> on: C:\ProgramData\Miniconda3\pkgs\conda-4.7.12-py36_0\info\test\tests\data\tar_traversal\absolute2.tar

!!!!!!!!!!!!!!!!!!!!!! Exception: <class 'shutil.ReadError'> on: C:\ProgramData\Miniconda3\envs\jupy3\Lib\site-packages\statsmodels\datasets\tests\raw.github.com,vincentarelbundock,Rdatasets,master,csv,car,Duncan.csv.zip
!!!!!!!!!!!!!!!!!!!!!! Exception: <class 'shutil.ReadError'> on: C:\ProgramData\Miniconda3\envs\jupy3\Lib\site-packages\statsmodels\datasets\tests\raw.github.com,vincentarelbundock,Rdatasets,master,datasets.csv.zip
!!!!!!!!!!!!!!!!!!!!!! Exception: <class 'shutil.ReadError'> on: C:\ProgramData\Miniconda3\envs\jupy3\Lib\site-packages\statsmodels\datasets\tests\raw.github.com,vincentarelbundock,Rdatasets,master,doc,car,rst,Duncan.rst.zip
!!!!!!!!!!!!!!!!!!!!!! Exception: <class 'shutil.ReadError'> on: C:\ProgramData\Miniconda3\pkgs\statsmodels-0.9.0-py36h452e1ab_0\Lib\site-packages\statsmodels\datasets\tests\raw.github.com,vincentarelbundock,Rdatasets,master,csv,car,Duncan.csv.zip
!!!!!!!!!!!!!!!!!!!!!! Exception: <class 'shutil.ReadError'> on: C:\ProgramData\Miniconda3\pkgs\statsmodels-0.9.0-py36h452e1ab_0\Lib\site-packages\statsmodels\datasets\tests\raw.github.com,vincentarelbundock,Rdatasets,master,datasets.csv.zip
!!!!!!!!!!!!!!!!!!!!!! Exception: <class 'shutil.ReadError'> on: C:\ProgramData\Miniconda3\pkgs\statsmodels-0.9.0-py36h452e1ab_0\Lib\site-packages\statsmodels\datasets\tests\raw.github.com,vincentarelbundock,Rdatasets,master,doc,car,rst,Duncan.rst.zip

!!!!!!!!!!!!!!!!!!!!!! Exception: <class 'FileExistsError'> on: C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems\rubyzip-1.2.2\test\data\path_traversal\jwilk\dirsymlink.zip
!!!!!!!!!!!!!!!!!!!!!! Exception: <class 'FileExistsError'> on: C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems\rubyzip-1.2.2\test\data\path_traversal\jwilk\dirsymlink2a.zip
!!!!!!!!!!!!!!!!!!!!!! Exception: <class 'FileExistsError'> on: C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems\rubyzip-1.2.2\test\data\path_traversal\jwilk\dirsymlink2b.zip
!!!!!!!!!!!!!!!!!!!!!! Exception: <class 'FileExistsError'> on: C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems\rubyzip-1.2.2\test\data\path_traversal\tuzovakaoff\symlink.zip

!!!!!!!!!!!!!!!!!!!!!! Exception: <class 'RuntimeError'> on: C:\Ruby25-x64\lib\ruby\gems\2.5.0\gems\rubyzip-1.2.2\test\data\zipWithEncryption.zip
